coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 70%
  precision: 1
  round: down
  range: "50...80"

comment:
  layout: "header, diff, files, footer"
  behavior: default
  require_changes: false

flag_management:
  default_rules:
    carryforward: true
